apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    tags.datadoghq.com/env: dev 
    tags.datadoghq.com/service: node-app 
    tags.datadoghq.com/version: "1.0" 
    tags.datadoghq.com/dd-team: "theAteam" 
    test: podlevel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
        tags.datadoghq.com/env: dev 
        tags.datadoghq.com/service: node-app 
        tags.datadoghq.com/version: "1.1"
        tags.datadoghq.com/dd-team: "theAteam" 
        test: podlevel
    spec:
      containers:
      - name: node-app
        image: ethomatos/node-app
        ports:
        - containerPort: 3000
        env:
        - name: DD_ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/version']
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: DD-TEAM
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/dd-team']
        - name: DD_PROFILING_ENABLED
          value: "true"
